sudo: true
language: haskell

git:
  depth: 5

cabal: "3.2"

cache:
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:
  # Stack
  - ghc: 8.10.3
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

install:
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --version
  - stack build --system-ghc --test --no-run-tests --bench --no-run-benchmarks

script:
  # HLint check
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint .
  - stack test --system-ghc

notifications:
  email: false
